WebParser/Controllers/PublicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebParser;
using PagedList.Mvc;
using PagedList;
using OfficeOpenXml;
using System.Drawing;
using OfficeOpenXml.Style;
using System.Reflection;

namespace WebParser.Controllers
{
    public class PublicationsController : Controller
    {
        private u0979199_springer_dataEntities1 db = new u0979199_springer_dataEntities1();

        // GET: Publications
        [HttpGet]
        public ActionResult Index(string searchText, string message, List<publications> list, int? i, bool update = false, int id = 0, int minYear = 1, int auNum = -1, string soString = "Empty", string typeString = "NoType", string word = "")
        {
            if (searchText != null)
            {
                searchText = searchText.ToLower();
            }
            ViewData["Titlesss"] = "";
            string messageType = null;
            if (update && db.publications.Count((a) => a.id == id) == 1)
            {
                publications targetPublication = db.publications.Find(id);
                if (targetPublication != null)
                {
                    ViewData["Titlesss"] = targetPublication.title;
                    ViewData["Year"] = targetPublication.year;
                    ViewData["Update"] = update;
                    ViewData["Id"] = id;
                    var queryUnique = from pub in db.publications
                                      where pub.authors.Count != 0 && pub.sources.Count != 0 && pub.id == id
                                      orderby pub.title
                                      select new
                                      {
                                          Title = pub.title,
                                          Authors = from p in db.publications
                                                    from author in p.authors
                                                    where p.id == pub.id && p.authors.Count() != 0
                                                    orderby author.initials
                                                    select author.initials,
                                          Sources = from p in db.publications
                                                    from sourc in p.sources
                                                    where p.id == pub.id && p.sources.Count() != 0
                                                    orderby sourc.item_title
                                                    select sourc.item_title,
                                          Issue = from p in db.publications
                                                  from sourc in p.sources
                                                  where p.id == pub.id && p.sources.Count() != 0
                                                  orderby sourc.journal_issue
                                                  select sourc.journal_issue,
                                          Volume = from p in db.publications
                                                   from sourc in p.sources
                                                   where p.id == pub.id && p.sources.Count() != 0
                                                   orderby sourc.journal_volume
                                                   select sourc.journal_volume,
                                          Year = pub.year,
                                          Words = pub.keywords.Select(x => x.keyword)
                                      };
                    DataTable result = LINQResultToDataTable(queryUnique);
                    ViewBag.QueryResult = result;
                }
            }
            if (message != null)
            {
                if (message == "Произошла ошибка или запись уже есть." || message == "Произошла непредвиденная ошибка." || message == "Произошла непредвиденная ошибка или такая публикация уже есть.")
                {
                    messageType = "danger";
                }
                else messageType = "success";
                ViewData["messageType"] = messageType;
                ViewData["message"] = message;
            }
            var authors = from au in db.authors
                          orderby au.initials
                          select au.initials;
            ViewBag.authors = authors;
            var source = from s in db.sources
                         orderby s.item_title
                         select s.item_title;
            ViewBag.source = source;
            var type = from t in db.types
                       orderby t.type_name
                       select t.type_name;
            ViewBag.type = type;

            return View((db.publications.Where(publications => (publications.title.ToLower().Contains(searchText) || searchText == null) && (publications.year == minYear || minYear == 1) && (publications.authors.Count() == auNum || auNum == -1)).OrderBy(x => x.title).ToList().ToPagedList(i ?? 1, 10)));
        }

        [HttpPost]
        public ActionResult Create(string titleInput, int yearInput, string[] Authors, string Words, string Source, string Type, int issueInput = 0, int volumeInput = 0)
        {
            string localMessage = "Произошла ошибка или запись уже есть.";
            List<int> authorId = GetAuthors(Authors);
            string[] words = GetKeywords(Words);

            try
            {
                if (ModelState.IsValid && db.publications.Count((a) => a.title == titleInput) == 0 && authorId.Count != 0)
                {
                    int current_id = db.publications.Count();
                    while (db.publications.Count((a) => a.id == current_id) == 1) { current_id++; }
                    publications newPublication = new publications();

                    newPublication.id = current_id;
                    newPublication.title = titleInput;
                    newPublication.year = Convert.ToInt16(yearInput);
                    foreach (int authorid in authorId)
                    {
                        authors a = db.authors.Find(authorid);
                        if (a != null)
                        {
                            newPublication.authors.Add(a);
                            a.publications.Add(newPublication);
                        }
                    }
                    foreach (string keyword in words)
                    {
                        keywords k = db.keywords.Where(x => x.keyword == keyword).FirstOrDefault();
                        if (k == null)
                        {
                            int k_id = db.keywords.Count();
                            while (db.keywords.Count((a) => a.id == k_id) == 1) { k_id++; }
                            k = new keywords();
                            k.id = k_id;
                            k.keyword = keyword;
                            db.keywords.Add(k);
                            db.SaveChanges();
                        }
                        newPublication.keywords.Add(k);
                        k.publications.Add(newPublication);
                    }
                    sources s = db.sources.Where(x => x.item_title == Source).FirstOrDefault();
                    if (s != null)
                    {
                        newPublication.sources.Add(s);
                        if (issueInput > 0 && volumeInput > 0)
                        {
                            s.journal_issue = issueInput;
                            s.journal_volume = volumeInput;
                        }
                        else
                        {
                            s.journal_issue = null;
                            s.journal_volume = null;
                        }
                        s.publications.Add(newPublication);
                    }
                    types t = db.types.Where(x => x.type_name == Type).FirstOrDefault();
                    if (t != null)
                    {
                        newPublication.types.Add(t);
                        t.publications.Add(newPublication);
                    }

                    db.publications.Add(newPublication);
                    db.SaveChanges();
                    localMessage = $"Запись {titleInput} успешно добавлена.";
                }
            }
            catch
            {

            }
            return RedirectToAction("/Index", new { i = 1, message = localMessage });
        }

        // GET: Publications/Edit/5
        public ActionResult Edit(int? id)
        {
            string localMessage = "Произошла непредвиденная ошибка.";
            if (id != null)
            {
                publications targetPublication = db.publications.Find(id);
                if (targetPublication != null)
                {
                    return RedirectToAction("/Index", new { i = 1, id = id, update = true });
                }
            }
            return RedirectToAction("/Index", new { i = 1, message = localMessage });
        }

        [HttpPost]
        public ActionResult Update(string titleInput, int idInput, int yearInput, string[] Authors, string Words, string Source, string Type, int issueInput = 0, int volumeInput = 0)
        {
            List<int> authorId = GetAuthors(Authors);
            string[] words = GetKeywords(Words);
            string localMessage = "Произошла непредвиденная ошибка или такая публикация уже есть.";
            try
            {
                if (ModelState.IsValid && db.publications.Count((a) => a.id == idInput) == 1 && db.publications.Count((a) => (a.title == titleInput) && (a.year == yearInput)) == 0)
                {
                    publications targetPublication = db.publications.Find(idInput);
                    localMessage = $"Запись {targetPublication.title} успешно изменена на {titleInput}.";

WebParser/Views/Publications/Index.cshtml
@model IPagedList<WebParser.publications>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@using PagedList.Mvc;
@using PagedList;
@using System.Collections;
@{
    ViewBag.Title = "Публикации";
}
<!DOCTYPE html>

<html>
<body>
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <a href="/Publications/Index" class="col-form-label">
                    <h3 class="text-center mt-2">Публикации</h3>
                    <hr />
                </a>
                @if (ViewData["messageType"] != null && ViewData["message"] != null)
                {
                    <div class="alert alert-@ViewData["messageType"] alert-dismissible text-center">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <b>@ViewData["message"]</b>
                    </div>
                }

            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                @if (ViewData["Update"] != null && ViewData["Titlesss"] != null)
                {
                    <h3 class="text-center text-info">
                        Изменить Публикацию
                    </h3>
                }
                else
                {
                    <h3 class="text-center text-info">
                        Добавить Публикацию
                    </h3>
                }

                <form action="" method="post" class="needs-validation" name="main" novalidate>
                    <div class="form-group">
                        <div class="form-group">
                            <input type="text" name="titleInput" class="form-control" placeholder="Заголовок" value="@ViewData["Titlesss"]" maxlength="200" required />
                            <div class="invalid-feedback">
                                Введите менее 200 символов
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="number" name="volumeInput" class="form-control" placeholder="Номер серии" value="@ViewData["Volume"]" min="0" max="9999" maxlength="4" />
                            <div class="invalid-feedback">
                                Введите значение от 0 до 9999
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="number" name="issueInput" class="form-control" placeholder="Номер выпуска" value="@ViewData["Issue"]" min="0" max="9999" maxlength="4" />
                            <div class="invalid-feedback">
                                Введите значение от 0 до 9999
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="number" name="yearInput" class="form-control" placeholder="Год издания" value="@ViewData["Year"]" min="1900" max="2020" maxlength="4" required />
                            <div class="invalid-feedback">
                                Значение должно быть между 1900 и 2020 годами.
                            </div>
                        </div>
                        <div class="form-group">
                            <select id="Author" name="Authors[]" class="custom-select form-control" multiple>
                                <option selected value="Default">Выберите авторов</option>
                                @foreach (var item in ViewBag.authors)
                                {
                                    <option value="@item">@item</option>
                                }
                            </select>
                        </div>
                        <div class="form-group">
                            <input type="text" name="Words" class="form-control" placeholder="Ключевые слова (через ,)" value="" maxlength="60" required />
                            <div class="invalid-feedback">
                                Введите менее 60 символов
                            </div>
                        </div>
                        <div class="form-group">
                            <select id="Source" name="Source" class="custom-select form-control">
                                <option selected value="Default">Выберите источник</option>
                                @foreach (var item in ViewBag.source)
                                {
                                    <option value="@item">@item</option>
                                }
                            </select>
                        </div>
                        <div class="form-group">
                            <select id="Type" name="Type" class="custom-select form-control">
                                @foreach (var item in ViewBag.type)
                                {
                                    <option value="@item">@item</option>
                                }
                            </select>
                        </div>
                        @if (ViewData["Update"] != null && ViewData["Titlesss"] != null)
                        {
                            <input type="submit" name="editKeyword" class="btn btn-success btn-block" value="Изменить" formaction="@Url.Action("Update", "Publications", new { titleInput = Request.QueryString["titleInput"], idInput = ViewData["Id"], yearInput = ViewData["yearInput"]})" />
                        }
                        else
                        {
                            <input type="submit" name="addKeyword" class="btn btn-primary btn-block" value="Добавить" formaction="Create" />
                        }
                    </div>
                </form>
                <a class="btn btn-success btn-block" href="@Url.Action("Export", "Publications", new { searchText = Request.QueryString["searchText"], minYear = Request.QueryString["minYear"], auNum = Request.QueryString["auNum"] })">Экспорт в Excel</a>
            </div>
            <div class="col-md-8">
                <h3 class="text-center text-info">Записи в базе данных</h3>
                <button type="button" class="collapsible">Фильтр</button>
                <div class="content">
                    <div class="container-fluid">
                        <form action="@Url.Action("", "Publications/", new { i = 1, searchText = Request.QueryString["searchText"] })" method="get" class="needs-validation" novalidate>
                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <input class="form-control mr-lg-3" name="searchText" type="search" placeholder="Поиск по публикации" maxlength="50" aria-label="Search">
                                    <div class="invalid-feedback">
                                        Текст должен быть не больше 50 символов.
                                    </div>
                                </div>
                                <div class="form-group col-md-4">
                                    <input type="number" class="form-control" id="minYear" name="minYear" min="1900" max="2020" maxlength="4" placeholder="Год">
                                    <div class="invalid-feedback">
                                        Значение должно быть между 1900 и 2020 годами.
                                    </div>
                                </div>
                                <div class="form-group col-md-4">
                                    <input type="number" class="form-control" id="auNum" name="auNum" min="1" max="20" placeholder="Введите количество авторов">
                                    <div class="invalid-feedback">
                                        Количество не должно превышать 20.
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <button type="submit" class="btn btn-success btn-lg btn-block">Подтвердить</button>
                            </div>
                        </form>
                    </div>
                </div>
                @if (ViewBag.QueryResult != null)
                {
                    <table class="table table-hover table-dark table-bordered table-responsive-md" id="mainTable" name="mainTable">
                        <thead class="thead-dark">
                            <tr>
                                @foreach (System.Data.DataColumn drc in ViewBag.QueryResult.Columns)
                                {
                                    <th class="text-center" scope="col">
                                        <h3>@drc</h3>
                                    </th>
                                }
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (System.Data.DataRow drr in ViewBag.QueryResult.Rows)
                            {
                                <tr>
                                    @foreach (var item in drr.ItemArray)
                                    {
                                        <td>
                                            @if (item is IEnumerable && !(item is string))
                                            {
                                                IEnumerable enumerable = (item as IEnumerable);
                                                if (enumerable != null)
                                                {
                                                    foreach (var itemIn in enumerable)
                                                    {
                                                        <h5 class="text-center">@itemIn</h5>
                                                    }
                                                }
                                            }
                                            else
                                            {
                                                <h5 class="text-center">@item</h5>
                                            }
                                        </td>
                                    }
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                <table class="table table-hover table-dark table-bordered table-responsive-md">
                    <thead class="thead-dark">
                        <tr>
                            <th class="text-center">
                                <h4>Заголовок</h4>
                            </th>
                            <th class="text-center">
                                <h4>Год издания</h4>
                            </th>
                            <th class="text-center">
                                <h4>Действия</h4>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <h6 class="text-center mt-2">@Html.DisplayFor(modelItem => item.title)</h6>
                                </td>
                                <td>
                                    <h6 class="text-center mt-2">@Html.DisplayFor(modelItem => item.year)</h6>
                                </td>
                                <td>
                                    <div class="row">
                                        <div class="col">
                                            <button href="#" onclick="location.href='@Url.Action("Edit", "Publications", new {id = item.id})'" class="btn btn-warning btn-sm btn-block">Изменить/Посмотреть</button>
                                        </div>
                                        <div class="col">
                                            <button href="#" onclick="location.href='@Url.Action("Delete", "Publications", new {id = item.id})'" class="btn btn-danger btn-sm btn-block" style="height:100%;">Удалить</button>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

                @Html.PagedListPager(Model, i => Url.Action("", "Publications/", new { i, searchText = Request.QueryString["searchText"], minYear = Request.QueryString["minYear"], auNum = Request.QueryString["auNum"] }))

            </div>
        </div>
    </div>

    <script>

        var form = document.querySelector('.needs-validation');

        form.addEventListener('submit', function (event) {

            if (!form.checkValidity()) {
                event.preventDefault();
                event.stopPropagation();
            }
            form.classList.add('was-validated');
        })

        var coll = document.getElementsByClassName("collapsible");
        var i;

        for (i = 0; i < coll.length; i++) {
            coll[i].addEventListener("click", function () {
                this.classList.toggle("active");
                var content = this.nextElementSibling;
                if (content.style.display === "block") {
                    content.style.display = "none";
                } else {
                    content.style.display = "block";
                }
            });
        }
    </script>


</body>
</html>