WebParser/Controllers/KeywordsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebParser;
using PagedList.Mvc;
using PagedList;
using OfficeOpenXml;
using System.Drawing;
using OfficeOpenXml.Style;

namespace WebParser.Controllers
{
    public class KeywordsController : Controller
    {
        private u0979199_springer_dataEntities1 db = new u0979199_springer_dataEntities1();

        // GET: Keywords
        [HttpGet]
        public ActionResult Index(string searchText, string message, int? i, bool update = false, int id = 0)
        {
            if (searchText != null)
            {
                searchText = searchText.ToLower();
            }
            string messageType = null;
            if (update && db.keywords.Count((a) => a.id == id) == 1)
            {
                keywords targetKeyword = db.keywords.Find(id);
                if (targetKeyword != null)
                {
                    ViewData["Word"] = targetKeyword.keyword;
                    ViewData["Update"] = update;
                    ViewData["Id"] = id;
                }
            }
            if (message != null)
            {
                if (message == "Произошла ошибка или запись уже есть." || message == "Произошла непредвиденная ошибка." || message == "Произошла непредвиденная ошибка или такое слово уже есть.")
                {
                    messageType = "danger";
                }
                else messageType = "success";
                ViewData["messageType"] = messageType;
                ViewData["message"] = message;
            }
            return View((db.keywords.Where(word => word.keyword.ToLower().Contains(searchText) || searchText == null)).OrderBy(x => x.keyword).ToList().ToPagedList(i ?? 1, 10));
        }

        [HttpPost]
        public ActionResult Create(string keywordInput)
        {
            string localMessage = "Произошла ошибка или запись уже есть.";
            if (ModelState.IsValid && db.keywords.Count((a) => a.keyword == keywordInput) == 0)
            {
                int current_id = db.keywords.Count();
                while (db.keywords.Count((a) => a.id == current_id) == 1) { current_id++; }
                keywords newWord = new keywords();
                newWord.id = current_id;
                newWord.keyword = keywordInput;
                db.keywords.Add(newWord);
                db.SaveChanges();
                localMessage = $"Запись {keywordInput} успешно добавлена.";
            }
            return RedirectToAction("/Index", new { i = 1, message = localMessage });
        }

        // GET: Keywords/Edit/5
        public ActionResult Edit(int? id)
        {
            string localMessage = "Произошла непредвиденная ошибка.";
            if (id != null)
            {
                keywords targetWord = db.keywords.Find(id);
                if (targetWord != null)
                {
                    return RedirectToAction("/Index", new { i = 1, id = id, update = true });
                }
            }
            return RedirectToAction("/Index", new { i = 1, message = localMessage });
        }

        [HttpPost]
        public ActionResult Update(string keywordInput, int idInput)
        {
            string localMessage = "Произошла непредвиденная ошибка или такое слово уже есть.";
            if (ModelState.IsValid && db.keywords.Count((a) => a.id == idInput) == 1 && db.keywords.Count((a) => a.keyword == keywordInput) == 0)
            {
                keywords targetWord = db.keywords.Find(idInput);
                localMessage = $"Запись {targetWord.keyword} успешно изменена на {keywordInput}.";
                targetWord.keyword = keywordInput;
                db.Entry(targetWord).State = EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("/Index", new { i = 1, message = localMessage });
        }

        // GET: Keywords/Delete/5
        public ActionResult Delete(int? id)
        {
            string localMessage = null;
            if (id != null)
            {
                keywords targetWord = db.keywords.Find(id);
                if (targetWord != null)
                {
                    db.keywords.Remove(targetWord);
                    db.SaveChanges();
                    localMessage = $"Запись {targetWord.keyword} была успешно удалена.";
                    return RedirectToAction("/Index", new { i = 1, message = localMessage });
                }
            }
            localMessage = "Произошла непредвиденная ошибка.";
            return RedirectToAction("/Index", new { i = 1, message = localMessage });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public void Export()
        {
            var keywords = db.keywords.OrderBy(x => x.keyword);
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            ExcelPackage Ep = new ExcelPackage();
            ExcelWorksheet Sheet = Ep.Workbook.Worksheets.Add("Report");
            Sheet.Cells["A1"].Value = "Номер";
            Sheet.Cells["B1"].Value = "Слово";
            int row = 2;
            foreach (var item in keywords)
            {
                Sheet.Cells[string.Format("A{0}", row)].Value = item.id;
                Sheet.Cells[string.Format("B{0}", row)].Value = item.keyword;
                row++;
            }
            Sheet.Cells["A:AZ"].AutoFitColumns();
            var cellFont = Sheet.Cells["A:AZ"].Style.Font;
            cellFont.SetFromFont(new Font("Times New Roman", 12));
            cellFont.Bold = true;
            Sheet.Cells["A:AZ"].Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;

            Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.AddHeader("content-disposition", "attachment: filename=" + "Ключевые слова.xlsx");
            Response.BinaryWrite(Ep.GetAsByteArray());
            Response.End();
        }
    }
}

WebParser/Views/Keywords/Index.cshtml
@model IPagedList<WebParser.keywords>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@using PagedList.Mvc;
@using PagedList;
@{
    ViewBag.Title = "Ключевые слова";
}
<!DOCTYPE html>

<html>
<body>
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <a href="/Keywords/Index" class="col-form-label">
                    <h3 class="text-center mt-2">Ключевые слова</h3>
                    <hr />
                </a>
                @if (ViewData["messageType"] != null && ViewData["message"] != null)
                {
                    <div class="alert alert-@ViewData["messageType"] alert-dismissible text-center">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <b>@ViewData["message"]</b>
                    </div>
                }

            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                @if (ViewData["Update"] != null && ViewData["Word"] != null)
                {
                    <h3 class="text-center text-info">
                        Изменить ключевое слово
                    </h3>
                }
                else
                {
                    <h3 class="text-center text-info">
                        Добавить ключевое слово
                    </h3>
                }
                <form action="" method="post" class="needs-validation" name="main" novalidate>
                    <div class="form-group">
                        <div class="form-group">
                            <input type="text" name="keywordInput" class="form-control" placeholder="Введите слово" value="@ViewData["Word"]" maxlength="15" required />
                            <div class="invalid-feedback">
                                Введите слово не более, чем в 15 символов
                            </div>
                        </div>
                        @if (ViewData["Update"] != null && ViewData["Word"] != null)
                        {
                            <input type="submit" name="editKeyword" class="btn btn-success btn-block" value="Изменить" formaction="@Url.Action("Update", "Keywords", new { keywordInput = Request.QueryString["keywordInput"], idInput = ViewData["Id"]})" />
                        }
                        else
                        {
                            <input type="submit" name="addKeyword" class="btn btn-primary btn-block" value="Добавить" formaction="Create" />
                        }
                    </div>
                </form>
                <form action="Index">
                    <div class="form-group">
                        <input class="form-control mr-lg-3" name="searchText" type="search" placeholder="Поиск по слову" aria-label="Search">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-warning btn-block" type="submit">Найти</button>
                    </div>
                </form>
                <a class="btn btn-success btn-block" href="@Url.Action("Export", "Keywords")">Экспорт в Excel</a>
            </div>
            <div class="col-md-8">
                <h3 class="text-center text-info">Записи в базе данных</h3>
                <table class="table table-hover table-dark table-bordered table-responsive-md">
                    <thead class="thead-dark">
                        <tr>
                            <th class="text-center">
                                <h3>Ключевое слово</h3>
                            </th>
                            <th class="text-center">
                                <h3>Действия</h3>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <h5 class="text-center mt-2">@Html.DisplayFor(modelItem => item.keyword)</h5>
                                </td>
                                <td>
                                    <div class="row">
                                        <div class="col">
                                            <button href="#" onclick="location.href='@Url.Action("Edit", "Keywords", new {id = item.id})'" class="btn btn-warning btn-block mt-2">Изменить</button>
                                        </div>
                                        <div class="col">
                                            <button href="#" onclick="location.href='@Url.Action("Delete", "Keywords", new {id = item.id})'" class="btn btn-danger btn-block mt-2">Удалить</button>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

                @Html.PagedListPager(Model, i => Url.Action("", "Keywords/", new { i, searchText = Request.QueryString["searchText"] }))

            </div>
        </div>
    </div>

    <script>

        var form = document.querySelector('.needs-validation');

        form.addEventListener('submit', function (event) {

            if (!form.checkValidity()) {
                event.preventDefault();
                event.stopPropagation();
            }
            form.classList.add('was-validated');
        })
    </script>


</body>
</html>