WebParser/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebParser;
using PagedList.Mvc;
using PagedList;
using System.Data.SqlClient;
using System.Runtime.CompilerServices;
using System.Web.UI.WebControls;
using OfficeOpenXml;
using System.Drawing;
using OfficeOpenXml.Style;

namespace WebParser.Controllers
{
    public class AuthorController : Controller
    {
        private u0979199_springer_dataEntities1 db = new u0979199_springer_dataEntities1();

        // GET: Author/Index/
        [HttpGet]
        public ActionResult Index(string searchText, string message, int? i, bool update = false, int id = 0)
        {
            if (searchText != null)
            {
                searchText = searchText.ToLower();
            }
            string messageType = null;
            if (update && db.authors.Count((a) => a.id == id) == 1)
            {
                authors targetAuthor = db.authors.Find(id);
                if (targetAuthor != null)
                {
                    ViewData["Initials"] = targetAuthor.initials;
                    ViewData["Update"] = update;
                    ViewData["Id"] = id;
                }
            }
            if (message != null)
            {
                if (message == "Произошла ошибка или запись уже есть." || message == "Произошла непредвиденная ошибка." || message == "Произошла непредвиденная ошибка или автор с таким именем уже есть.")
                {
                    messageType = "danger";
                }
                else messageType = "success";
                ViewData["messageType"] = messageType;
                ViewData["message"] = message;
            }
            return View((db.authors.Where(author => author.initials.ToLower().Contains(searchText) || searchText == null)).OrderBy(x => x.initials).ToList().ToPagedList(i ?? 1, 10));
        }

        [HttpPost]
        public ActionResult Create(string authorInput)
        {
            string localMessage = "Произошла ошибка или запись уже есть.";
            if (ModelState.IsValid && db.authors.Count((a) => a.initials == authorInput) == 0)
            {
                int current_id = db.authors.Count();
                while (db.authors.Count((a) => a.id == current_id) == 1) { current_id++; }
                authors newAuthor = new authors();
                newAuthor.id = current_id;
                newAuthor.initials = authorInput;
                db.authors.Add(newAuthor);
                db.SaveChanges();
                localMessage = $"Запись {authorInput} успешно добавлена.";
            }
            return RedirectToAction("/Index", new { i = 1, message = localMessage });
        }

        // GET: Author/Edit/5
        public ActionResult Edit(int? id)
        {
            string localMessage = "Произошла непредвиденная ошибка.";
            if (id != null)
            {
                authors targetAuthor = db.authors.Find(id);
                if (targetAuthor != null)
                {
                    return RedirectToAction("/Index", new { i = 1, id = id, update = true });
                }
            }
            return RedirectToAction("/Index", new { i = 1, message = localMessage });
        }

        [HttpPost]
        public ActionResult Update(string authorInput, int idInput)
        {
            string localMessage = "Произошла непредвиденная ошибка или автор с таким именем уже есть.";
            if (ModelState.IsValid && db.authors.Count((a) => a.id == idInput) == 1 && db.authors.Count((a) => a.initials == authorInput) == 0)
            {
                authors targetAuthor = db.authors.Find(idInput);
                localMessage = $"Запись {targetAuthor.initials} успешно изменена на {authorInput}.";
                targetAuthor.initials = authorInput;
                db.Entry(targetAuthor).State = EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("/Index", new { i = 1, message = localMessage });
        }

        // GET: Author/Delete/5
        public ActionResult Delete(int? id)
        {
            string localMessage = null;
            if (id != null)
            {
                authors targetAuthor = db.authors.Find(id);
                if (targetAuthor != null)
                {
                    db.authors.Remove(targetAuthor);
                    db.SaveChanges();
                    localMessage = $"Запись {targetAuthor.initials} была успешно удалена.";
                    return RedirectToAction("/Index", new { i = 1, message = localMessage });
                }
            }
            localMessage = "Произошла непредвиденная ошибка.";
            return RedirectToAction("/Index", new { i = 1, message = localMessage });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public void Export()
        {
            var authors = db.authors.OrderBy(x => x.initials);
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            ExcelPackage Ep = new ExcelPackage();
            ExcelWorksheet Sheet = Ep.Workbook.Worksheets.Add("Report");
            Sheet.Cells["A1"].Value = "Номер";
            Sheet.Cells["B1"].Value = "Полное имя";
            int row = 2;
            foreach (var item in authors)
            {
                Sheet.Cells[string.Format("A{0}", row)].Value = item.id;
                Sheet.Cells[string.Format("B{0}", row)].Value = item.initials;
                row++;
            }
            Sheet.Cells["A:AZ"].AutoFitColumns();
            var cellFont = Sheet.Cells["A:AZ"].Style.Font;
            cellFont.SetFromFont(new Font("Times New Roman", 12));
            cellFont.Bold = true;
            Sheet.Cells["A:AZ"].Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;

            Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.AddHeader("content-disposition", "attachment: filename=" + "Авторы.xlsx");
            Response.BinaryWrite(Ep.GetAsByteArray());
            Response.End();
        }
    }
}

WebParser/Views/Author/Index.cshtml
@model IPagedList<WebParser.authors>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@using PagedList.Mvc;
@using PagedList;
@{
    ViewBag.Title = "Авторы";
}
<!DOCTYPE html>

<html>
<body>
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <a href="/Author/Index" class="col-form-label">
                    <h3 class="text-center mt-2">Авторы</h3>
                    <hr />
                </a>
                @if (ViewData["messageType"] != null && ViewData["message"] != null)
                {
                    <div class="alert alert-@ViewData["messageType"] alert-dismissible text-center">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <b>@ViewData["message"]</b>
                    </div>
                }

            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                @if (ViewData["Update"] != null && ViewData["Initials"] != null)
                {
                    <h3 class="text-center text-info">
                        Изменить автора
                    </h3>
                }
                else
                {
                    <h3 class="text-center text-info">
                        Добавить автора
                    </h3>
                }
                <form action="" method="post" class="needs-validation" name="main" novalidate>
                    <div class="form-group">
                        <div class="form-group">
                            <input type="text" name="authorInput" class="form-control" placeholder="Введите полное имя" value="@ViewData["Initials"]" maxlength="40" required />
                            <div class="invalid-feedback">
                                Введите имя, не превышающее 40 символов
                            </div>
                        </div>
                        @if (ViewData["Update"] != null && ViewData["Initials"] != null)
                        {
                            <input type="submit" name="editAuthor" class="btn btn-success btn-block" value="Изменить" formaction="@Url.Action("Update", "Author", new { authorInput = Request.QueryString["authorInput"], idInput = ViewData["Id"]})" />
                        }
                        else
                        {
                            <input type="submit" name="addAuthor" class="btn btn-primary btn-block" value="Добавить" formaction="Create" />
                        }
                    </div>
                </form>
                <form action="Index">
                    <div class="form-group">
                        <input class="form-control mr-lg-3" name="searchText" type="search" placeholder="Поиск по имени" aria-label="Search">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-warning btn-block" type="submit">Найти</button>
                    </div>
                </form>
                <a class="btn btn-success btn-block" href="@Url.Action("Export", "Author")">Экспорт в Excel</a>
            </div>
            <div class="col-md-8">
                <h3 class="text-center text-info">Записи в базе данных</h3>
                <table class="table table-hover table-dark table-bordered table-responsive-md">
                    <thead class="thead-dark">
                        <tr>
                            <th class="text-center">
                                <h3>Имя Автора</h3>
                            </th>
                            <th class="text-center">
                                <h3>Действия</h3>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <h5 class="text-center mt-2">@Html.DisplayFor(modelItem => item.initials)</h5>
                                </td>
                                <td>
                                    <div class="row">
                                        <div class="col">
                                            <button href="#" onclick="location.href='@Url.Action("Edit", "Author", new {id = item.id})'" class="btn btn-warning btn-block mt-2">Изменить/Посмотреть</button>
                                        </div>
                                        <div class="col">
                                            <button href="#" onclick="location.href='@Url.Action("Delete", "Author", new {id = item.id})'" class="btn btn-danger btn-block mt-2">Удалить</button>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

                @Html.PagedListPager(Model, i => Url.Action("", "Author/", new { i, searchText = Request.QueryString["searchText"] }))

            </div>
        </div>
    </div>

    <script>

        var form = document.querySelector('.needs-validation');

        form.addEventListener('submit', function (event) {

            if (!form.checkValidity()) {
                event.preventDefault();
                event.stopPropagation();
            }
            form.classList.add('was-validated');
        })
    </script>


</body>
</html>